name       : python-configobj
version    : 5.0.8
release    : 9
source     :
    - https://github.com/DiffSK/configobj/archive/v5.0.8.tar.gz : 547dc047e31c71d7a8732016336769ed450588f34a7c13077aa7acc7df245eda
homepage   : https://github.com/DiffSK/configobj
license    : BSD-3-Clause
component  : programming.python
summary    : Config file reading, writing, and validation
description: |
    ConfigObj is a simple but powerful configuration file reader and writer: an ini file round tripper. Its main feature is that it is very easy to use, with a straightforward programmers interface and a simple syntax for config files.
builddeps  :
    - python-pytest # check
rundeps    :
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
